// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scwknownjilcsfcuqouy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjd2tub3duamlsY3NmY3Vxb3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNTkyOTAsImV4cCI6MjA1MTYzNTI5MH0.-MLXdiXMdLVPDLfJd0-laLt2gpY8YuKp3ptkXdY5XW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);